python src/semantic_editing_search_v1.py \
  --dataset               fashioniq \
  --dataset_path          FashionIQ_cap_num_15_split1 \
  --gpt_version           gpt-3.5 \
  --submission_name       "cap_num_15_split1" \
  --gpt_version           gpt-3.5\
  --caption_type          opt \
  --use_momentum_strategy True \
  --pos_factor            0.5 \
  --neg_factor            0 \
  --nums_caption          7